# Plugins
gems: [Jekyll-minibundle, jekyll-multiple-languages]

# Site settings
title: Mads Buch
email: madspbuch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on life.
baseurl: "/life" # the subpath of your site, e.g. /blog/
url: "http://madsbuch.com" # the base hostname & protocol for your site
twitter_username: madspbuch
github_username:  madsbuch

# Build settings
markdown: kramdown


paginate: 4
paginate_path: "blog/page:num"
